Repository toduck-App/toduck-backend, pull requests merged in 2024-07, with the labels that each got.

#2 SQL DDL 작성
  rule-config/naver-intellij-formatter.xml
  sql/init.sql
  src/main/resources/application-local.yml
Labels: ✨ Feature, 🚧 Infrastructure

#3 ERD 엔티티 매핑
  rule-config/naver-checkstyle-rules.xml
  sql/init.sql
  src/main/java/im/toduck/domain/persistence/entity/person/Alarm.java
  src/main/java/im/toduck/domain/persistence/entity/person/Color.java
  src/main/java/im/toduck/domain/persistence/entity/person/Day.java
  src/main/java/im/toduck/domain/persistence/entity/person/Emoji.java
  src/main/java/im/toduck/domain/persistence/entity/person/RepeatDay.java
  src/main/java/im/toduck/domain/persistence/entity/person/RepeatDayLink.java
  src/main/java/im/toduck/domain/persistence/entity/person/Routine.java
  src/main/java/im/toduck/domain/persistence/entity/person/Schedule.java
  src/main/java/im/toduck/domain/persistence/entity/person/SharedRoutine.java
  src/main/java/im/toduck/domain/persistence/entity/social/Comment.java
  src/main/java/im/toduck/domain/persistence/entity/social/Like.java
  src/main/java/im/toduck/domain/persistence/entity/social/Social.java
  src/main/java/im/toduck/domain/persistence/entity/social/SocialCategory.java
  src/main/java/im/toduck/domain/persistence/entity/social/SocialCategoryLink.java
  src/main/java/im/toduck/domain/persistence/entity/social/SocialImageFile.java
  src/main/java/im/toduck/domain/persistence/entity/social/SocialTag.java
  src/main/java/im/toduck/domain/persistence/entity/user/Emotion.java
  src/main/java/im/toduck/domain/persistence/entity/user/Follow.java
  src/main/java/im/toduck/domain/persistence/entity/user/OAuthProvider.java
  src/main/java/im/toduck/domain/persistence/entity/user/Record.java
  src/main/java/im/toduck/domain/persistence/entity/user/User.java
  src/main/java/im/toduck/global/base/entity/BaseEntity.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: ⚙️ Configuration

#4 공통응답형식 설계 및 에러코드 양식 작성 및 개발
  src/main/java/im/toduck/global/config/json/JsonConfig.java
  src/main/java/im/toduck/global/config/json/StringStripJsonDeserializer.java
  src/main/java/im/toduck/global/exception/CommonException.java
  src/main/java/im/toduck/global/exception/ExceptionCode.java
  src/main/java/im/toduck/global/exception/VoException.java
  src/main/java/im/toduck/global/handler/CustomParameterHandler.java
  src/main/java/im/toduck/global/handler/GlobalExceptionHandler.java
  src/main/java/im/toduck/global/presentation/ApiResponse.java
  src/main/java/im/toduck/global/presentation/builder/ApiResponseEntityBuilder.java
  src/test/java/im/toduck/global/ExceptionCodeTest.java
  src/test/java/im/toduck/global/presentation/ApiResponseTest.java
Labels: ✨ Feature
