Repository toduck-App/toduck-backend, pull requests merged in 2024-10, with the labels that each got.

#23 도메인 로깅 AOP 적용
  build.gradle
  src/main/java/im/toduck/global/annotation/log/ExceptionLogExplanation.java
  src/main/java/im/toduck/global/annotation/log/GeneralLogExplanation.java
  src/main/java/im/toduck/global/annotation/log/LogExplanations.java
  src/main/java/im/toduck/global/aop/log/LocalLogAspect.java
  src/main/java/im/toduck/global/aop/log/ProdLogAspect.java
  src/main/java/im/toduck/global/aop/log/pointcut/LogPointCut.java
  src/main/java/im/toduck/global/log/layout/MaskingPatternLayout.java
  src/main/java/im/toduck/global/log/properties/ExceptionLogProperty.java
  src/main/java/im/toduck/global/log/properties/InfoLogProperty.java
  src/main/java/im/toduck/global/log/properties/LogProperty.java
  src/main/java/im/toduck/global/log/vo/LogLevel.java
  src/main/resources/application-prod.yml
  src/main/resources/log/log-local.xml
  src/main/resources/log/log-prod.xml
  src/main/resources/logback.xml
  src/test/java/im/toduck/architecture/main/domain/presentation/ControllerRulesTest.java
  src/test/resources/application-test.yml
Labels: ✨ Feature

#28 SQL 로깅 설정 추가 및 N+1 문제 해결
  .gitignore
  build.gradle
  src/main/java/im/toduck/domain/routine/persistence/repository/querydsl/RoutineRecordRepositoryCustomImpl.java
  src/main/java/im/toduck/global/config/logging/P6SpyConfig.java
  src/main/java/im/toduck/global/config/logging/P6SpyEventListener.java
  src/main/java/im/toduck/global/config/logging/P6SpyFormatter.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: ✨ Feature, 🔨 Refactor

#29 AOP 로 적용된 로그에서 null 에러 해결
  src/main/java/im/toduck/global/aop/log/LocalLogAspect.java
  src/main/java/im/toduck/global/aop/log/ProdLogAspect.java
  src/main/java/im/toduck/global/log/properties/InfoLogProperty.java
Labels: 🐛 Bug
