Repository toduck-App/toduck-backend, pull requests merged in 2025-06, with the labels that each got.

#113 닉네임 자동 생성 규칙 및 후보 변경
  src/main/java/im/toduck/domain/auth/domain/service/NickNameGenerateService.java
Labels: 🔨 Refactor

#117 일기 작성 리마인더 스케줄러 구현
  build.gradle
  src/main/java/im/toduck/ToduckBackendApplication.java
  src/main/java/im/toduck/domain/diary/domain/usecase/DiarySchedulerUseCase.java
  src/main/java/im/toduck/domain/notification/domain/data/DiaryReminderData.java
  src/main/java/im/toduck/domain/notification/domain/event/DiaryReminderNotificationEvent.java
  src/main/java/im/toduck/domain/notification/domain/service/DeviceTokenService.java
  src/main/java/im/toduck/domain/notification/domain/service/PushNotificationService.java
  src/main/java/im/toduck/domain/notification/domain/usecase/NotificationUseCase.java
  src/main/java/im/toduck/domain/notification/persistence/repository/DeviceTokenRepository.java
  src/main/java/im/toduck/domain/user/domain/service/UserService.java
  src/main/java/im/toduck/domain/user/persistence/repository/querydsl/UserRepositoryCustom.java
  src/main/java/im/toduck/domain/user/persistence/repository/querydsl/UserRepositoryCustomImpl.java
  src/main/java/im/toduck/global/config/shedlock/ShedLockConfig.java
Labels: ✨ Feature

#119 일정 특정 날짜 이후 일괄 수정시에 발생하는 에러 해결
  src/main/java/im/toduck/domain/schedule/domain/service/ScheduleModifyService.java
  src/test/java/im/toduck/domain/schedule/domain/usecase/ScheduleUseCaseTest.java
Labels: 🐛 Bug
